### ISSUE TITLE
build(relay): support RustC 1.5x

### ISSUE THREAD

**Issue by petermetz** [hyperledger-labs/weaver-dlt-interoperability#115]
After downgrading to Rust `1.45` the build works fine.

Tried building on the latest stable at the time of this writing (`v1.53`) and the `lexical_core` create has some issues with usize -> i32 operations (division/implicit casts from what I can tell).

```sh
error[E0308]: mismatched types
  --> /******/.cargo/registry/src/github.com-1ecc6299db9ec823/lexical-core-0.6.2/src/atof/algorithm/bhcomp.rs:62:24
   |
62 |     let bytes = bits / Limb::BITS;
   |                        ^^^^^^^^^^ expected `usize`, found `u32`

error[E0277]: cannot divide `usize` by `u32`
  --> /******/.cargo/registry/src/github.com-1ecc6299db9ec823/lexical-core-0.6.2/src/atof/algorithm/bhcomp.rs:62:22
   |
62 |     let bytes = bits / Limb::BITS;
   |                      ^ no implementation for `usize / u32`
   |
   = help: the trait `Div<u32>` is not implemented for `usize`

error[E0308]: mismatched types
   --> /******/.cargo/registry/src/github.com-1ecc6299db9ec823/lexical-core-0.6.2/src/atof/algorithm/bigcomp.rs:158:55
    |
158 |     let nlz = den.leading_zeros().wrapping_sub(wlz) & (u32::BITS - 1);
    |                                                       ^^^^^^^^^^^^^^^ expected `usize`, found `u32`

error[E0277]: no implementation for `usize & u32`
   --> /******/.cargo/registry/src/github.com-1ecc6299db9ec823/lexical-core-0.6.2/src/atof/algorithm/bigcomp.rs:158:53
    |
158 |     let nlz = den.leading_zeros().wrapping_sub(wlz) & (u32::BITS - 1);
    |                                                     ^ no implementation for `usize & u32`
    |
    = help: the trait `BitAnd<u32>` is not implemented for `usize`

error[E0308]: mismatched types
   --> /******/.cargo/registry/src/github.com-1ecc6299db9ec823/lexical-core-0.6.2/src/atof/algorithm/bigcomp.rs:176:40
    |
176 |         let (q, r) = shift.ceil_divmod(Limb::BITS);
    |                                        ^^^^^^^^^^ expected `usize`, found `u32`
    |
help: you can convert a `u32` to a `usize` and panic if the converted value doesn't fit
    |
176 |         let (q, r) = shift.ceil_divmod(Limb::BITS.try_into().unwrap());
    |                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0308]: mismatched types
    --> /******/.cargo/registry/src/github.com-1ecc6299db9ec823/lexical-core-0.6.2/src/atof/algorithm/math.rs:1049:42
     |
1049 |     let mut count = index.saturating_mul(Limb::BITS);
     |                                          ^^^^^^^^^^ expected `usize`, found `u32`
     |
help: you can convert a `u32` to a `usize` and panic if the converted value doesn't fit
     |
1049 |     let mut count = index.saturating_mul(Limb::BITS.try_into().unwrap());
     |                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0308]: mismatched types
    --> /******/.cargo/registry/src/github.com-1ecc6299db9ec823/lexical-core-0.6.2/src/atof/algorithm/math.rs:1064:28
     |
1064 |     Limb::BITS.checked_mul(x.len())
     |                            ^^^^^^^ expected `u32`, found `usize`
     |
help: you can convert a `usize` to a `u32` and panic if the converted value doesn't fit
     |
1064 |     Limb::BITS.checked_mul(x.len().try_into().unwrap())
     |                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0308]: mismatched types
    --> /******/.cargo/registry/src/github.com-1ecc6299db9ec823/lexical-core-0.6.2/src/atof/algorithm/math.rs:1065:22
     |
1065 |         .map(|v| v - nlz)
     |                      ^^^ expected `u32`, found `usize`

error[E0277]: cannot subtract `usize` from `u32`
    --> /******/.cargo/registry/src/github.com-1ecc6299db9ec823/lexical-core-0.6.2/src/atof/algorithm/math.rs:1065:20
     |
1065 |         .map(|v| v - nlz)
     |                    ^ no implementation for `u32 - usize`
     |
     = help: the trait `Sub<usize>` is not implemented for `u32`

error[E0308]: mismatched types
    --> /******/.cargo/registry/src/github.com-1ecc6299db9ec823/lexical-core-0.6.2/src/atof/algorithm/math.rs:1066:20
     |
1066 |         .unwrap_or(usize::max_value())
     |                    ^^^^^^^^^^^^^^^^^^ expected `u32`, found `usize`
     |
help: you can convert a `usize` to a `u32` and panic if the converted value doesn't fit
     |
1066 |         .unwrap_or(usize::max_value().try_into().unwrap())
     |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0308]: mismatched types
    --> /******/.cargo/registry/src/github.com-1ecc6299db9ec823/lexical-core-0.6.2/src/atof/algorithm/math.rs:1064:5
     |
1060 |   pub fn bit_length(x: &[Limb]) -> usize {
     |                                    ----- expected `usize` because of return type
...
1064 | /     Limb::BITS.checked_mul(x.len())
1065 | |         .map(|v| v - nlz)
1066 | |         .unwrap_or(usize::max_value())
     | |______________________________________^ expected `usize`, found `u32`
     |
help: you can convert a `u32` to a `usize` and panic if the converted value doesn't fit
     |
1064 |     Limb::BITS.checked_mul(x.len())
1065 |         .map(|v| v - nlz)
1066 |         .unwrap_or(usize::max_value()).try_into().unwrap()
     |

error[E0308]: mismatched types
    --> /******/.cargo/registry/src/github.com-1ecc6299db9ec823/lexical-core-0.6.2/src/atof/algorithm/math.rs:1091:23
     |
1091 |     debug_assert!(n < bits && n != 0);
     |                       ^^^^ expected `usize`, found `u32`
     |
help: you can convert a `u32` to a `usize` and panic if the converted value doesn't fit
     |
1091 |     debug_assert!(n < bits.try_into().unwrap() && n != 0);
     |                       ^^^^^^^^^^^^^^^^^^^^^^^^

error[E0308]: mismatched types
    --> /******/.cargo/registry/src/github.com-1ecc6299db9ec823/lexical-core-0.6.2/src/atof/algorithm/math.rs:1098:25
     |
1098 |     let lshift = bits - n;
     |                         ^ expected `u32`, found `usize`

error[E0277]: cannot subtract `usize` from `u32`
    --> /******/.cargo/registry/src/github.com-1ecc6299db9ec823/lexical-core-0.6.2/src/atof/algorithm/math.rs:1098:23
     |
1098 |     let lshift = bits - n;
     |                       ^ no implementation for `u32 - usize`
     |
     = help: the trait `Sub<usize>` is not implemented for `u32`

error[E0308]: mismatched types
    --> /******/.cargo/registry/src/github.com-1ecc6299db9ec823/lexical-core-0.6.2/src/atof/algorithm/math.rs:1140:19
     |
1140 |     let rem = n % bits;
     |                   ^^^^ expected `usize`, found `u32`

error[E0277]: cannot mod `usize` by `u32`
    --> /******/.cargo/registry/src/github.com-1ecc6299db9ec823/lexical-core-0.6.2/src/atof/algorithm/math.rs:1140:17
     |
1140 |     let rem = n % bits;
     |                 ^ no implementation for `usize % u32`
     |
     = help: the trait `Rem<u32>` is not implemented for `usize`

error[E0308]: mismatched types
    --> /******/.cargo/registry/src/github.com-1ecc6299db9ec823/lexical-core-0.6.2/src/atof/algorithm/math.rs:1141:19
     |
1141 |     let div = n / bits;
     |                   ^^^^ expected `usize`, found `u32`

error[E0277]: cannot divide `usize` by `u32`
    --> /******/.cargo/registry/src/github.com-1ecc6299db9ec823/lexical-core-0.6.2/src/atof/algorithm/math.rs:1141:17
     |
1141 |     let div = n / bits;
     |                 ^ no implementation for `usize / u32`
     |
     = help: the trait `Div<u32>` is not implemented for `usize`

error[E0308]: mismatched types
    --> /******/.cargo/registry/src/github.com-1ecc6299db9ec823/lexical-core-0.6.2/src/atof/algorithm/math.rs:1197:23
     |
1197 |     debug_assert!(n < bits);
     |                       ^^^^ expected `usize`, found `u32`
     |
help: you can convert a `u32` to a `usize` and panic if the converted value doesn't fit
     |
1197 |     debug_assert!(n < bits.try_into().unwrap());
     |                       ^^^^^^^^^^^^^^^^^^^^^^^^

error[E0308]: mismatched types
    --> /******/.cargo/registry/src/github.com-1ecc6299db9ec823/lexical-core-0.6.2/src/atof/algorithm/math.rs:1207:25
     |
1207 |     let rshift = bits - n;
     |                         ^ expected `u32`, found `usize`

error[E0277]: cannot subtract `usize` from `u32`
    --> /******/.cargo/registry/src/github.com-1ecc6299db9ec823/lexical-core-0.6.2/src/atof/algorithm/math.rs:1207:23
     |
1207 |     let rshift = bits - n;
     |                       ^ no implementation for `u32 - usize`
     |
     = help: the trait `Sub<usize>` is not implemented for `u32`

error[E0308]: mismatched types
    --> /******/.cargo/registry/src/github.com-1ecc6299db9ec823/lexical-core-0.6.2/src/atof/algorithm/math.rs:1259:19
     |
1259 |     let rem = n % bits;
     |                   ^^^^ expected `usize`, found `u32`

error[E0277]: cannot mod `usize` by `u32`
    --> /******/.cargo/registry/src/github.com-1ecc6299db9ec823/lexical-core-0.6.2/src/atof/algorithm/math.rs:1259:17
     |
1259 |     let rem = n % bits;
     |                 ^ no implementation for `usize % u32`
     |
     = help: the trait `Rem<u32>` is not implemented for `usize`

error[E0308]: mismatched types
    --> /******/.cargo/registry/src/github.com-1ecc6299db9ec823/lexical-core-0.6.2/src/atof/algorithm/math.rs:1260:19
     |
1260 |     let div = n / bits;
     |                   ^^^^ expected `usize`, found `u32`

error[E0277]: cannot divide `usize` by `u32`
    --> /******/.cargo/registry/src/github.com-1ecc6299db9ec823/lexical-core-0.6.2/src/atof/algorithm/math.rs:1260:17
     |
1260 |     let div = n / bits;
     |                 ^ no implementation for `usize / u32`
     |
     = help: the trait `Div<u32>` is not implemented for `usize`

error[E0308]: mismatched types
    --> /******/.cargo/registry/src/github.com-1ecc6299db9ec823/lexical-core-0.6.2/src/atof/algorithm/math.rs:2071:27
     |
2071 |     let rs = Limb::BITS - s;
     |                           ^ expected `u32`, found `usize`

error[E0277]: cannot subtract `usize` from `u32`
    --> /******/.cargo/registry/src/github.com-1ecc6299db9ec823/lexical-core-0.6.2/src/atof/algorithm/math.rs:2071:25
     |
2071 |     let rs = Limb::BITS - s;
     |                         ^ no implementation for `u32 - usize`
     |
     = help: the trait `Sub<usize>` is not implemented for `u32`

error: aborting due to 27 previous errors

Some errors have detailed explanations: E0277, E0308.
For more information about an error, try `rustc --explain E0277`.
error: could not compile `lexical-core`

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: build failed
make: *** [Makefile:77: build-local] Error 101
```

**Comment by VRamakrishna** [comment]
It looks like there was a breaking change in Rustc `1.53.0`. The build works with `1.52.0` and below. We'll create an issue to add type checks to the code, and in the meantime, add instructions to install version `1.52.0` before building.

**Comment by VRamakrishna** [comment]
These errors was caused by issues in the `lexical-core` package, which is one of the Weaver relay dependencies, but the package has now been fixed, as explained in https://users.rust-lang.org/t/expected-u32-found-usize-in-lexical-core/62820.

Before rebuilding the relay, update Rust as follows:
```
rustup update
```

Update the `nom` and `lexical-core` packages in the following sequence:
```
cargo update -p nom
cargo update -p lexical-core
``

Rebuild the relay by running `make` from within the `core/relay` folder.

**Comment by VRamakrishna** [comment]
@petermetz Can you try the above instructions and close this issue if the problem is resolved?

**Comment by petermetz** [comment]
@VRamakrishna Thank you very much for the fix, it works now!
